name: 'Quality check'
on:
  push:
    branches:
      - master

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get install apt-rdepends
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[test]
          python -m pytest
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'